version: '3.7'

services:
  frontend:
    image: rxtrail-frontend
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rxtrail-frontend
    tty: true
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www/


